
[env:featheresp32v2]
platform = espressif32@^6.5.0
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=3
lib_deps =
	makuna/NeoPixelBus@^2.7.3

